name: setup-nix
author: Shikanime Studio
branding:
  icon: globe
  color: gray-dark
description: Setup Nix using Determinate Systems installer and cache
inputs:
  cachix-auth-token:
    description: Cachix auth token, used by the cachix-action
    required: false
    default: ""
  cachix-name:
    description: Cachix name, used by the cachix-action
    required: false
    default: ""
  extra-conf:
    description: Additional Nix configuration to append to nix.conf
    required: false
    default: ""
  extra-platforms:
    description: Space-separated Nix platforms to enable (e.g., aarch64-linux)
    required: false
    default: ""
  github-token:
    description: GitHub token, used by the Determinate Systems installer
    required: false
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    - uses: docker/setup-qemu-action@v3
      if: ${{ inputs.extra-platforms != '' }}
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ inputs.github-token }}
        extra_nix_config: |
          extra-platforms = ${{ inputs.extra-platforms }}
          ${{ inputs.extra-conf }}
    - uses: cachix/cachix-action@v15
      with:
        name: ${{ inputs.cachix-name }}
        authToken: ${{ inputs.cachix-auth-token }}
